from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (CustomUserViewSet, TagViewSet, IngredientViewSet,
                    RecipeViewSet)

# Create a router and register our viewsets with it.
router = DefaultRouter()
# User related endpoints (/users/, /users/{id}/, /users/me/, /users/subscriptions/, /users/{id}/subscribe/)
# Djoser's UserViewSet handles most of these, our CustomUserViewSet adds subscriptions/subscribe
router.register('users', CustomUserViewSet, basename='users')
# Tag endpoints (/tags/, /tags/{id}/) - ReadOnly
router.register('tags', TagViewSet, basename='tags')
# Ingredient endpoints (/ingredients/, /ingredients/{id}/) - ReadOnly with search
router.register('ingredients', IngredientViewSet, basename='ingredients')
# Recipe endpoints (/recipes/, /recipes/{id}/, /recipes/{id}/favorite/, /recipes/{id}/shopping_cart/, /recipes/download_shopping_cart/)
router.register('recipes', RecipeViewSet, basename='recipes')

# The API URLs are determined automatically by the router.
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),

    # Include Djoser's authentication token URLs (for login/logout)
    # This provides endpoints like /api/auth/token/login/ and /api/auth/token/logout/
    path('auth/', include('djoser.urls.authtoken')),

    # Djoser's base URLs (like /users/set_password/) are included via the router registration
    # path('', include('djoser.urls')), # No need to include this separately if using router
]